config/routes.rb
Rails.application.routes.draw do
  resources :chapters do
    resources :sections
  end

  resources :sections do
    resources :lessons
  end

  root :to => 'chapters#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  validates :name, :presence => true
  has_many :sections
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  validates :name, :content, :number, :presence => true
  belongs_to :section
end

app/models/section.rb
class Section < ActiveRecord::Base
  validates :name, :presence => true
  belongs_to :chapter
  has_many :lessons
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  def index
    @chapters = Chapter.all
  end

  def show
    @chapter = Chapter.find(params[:id])
  end

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def index
    @section = Section.find(params[:id])
    @lessons = Lesson.all
  end

  # passing in a parent object (above-> @section) in the view make this nesting work
  def show
    @section = Section.find(params[:section_id])
    @lesson = @section.lessons.find(params[:id])
  end

  def new
    @section = Section.find(params[:section_id])
    @lesson = @section.lessons.new
  end

  def create
    @section = Section.find(params[:section_id])
    @lesson = @section.lessons.new(lesson_params)
    if @lesson.save
      redirect_to chapter_path(@lesson.section.chapter)
    else
      render :new
    end
  end

  def edit
    @lesson = Lesson.find(params[:id])
    @section = @lesson.section
  end

  def update
    @section = Section.find(params[:section_id])
    @lesson = Lesson.find(params[:id])
    if @lesson.update(lesson_params)
      redirect_to chapter_path(@lesson.section.chapter)
    else
      render :edit
    end
  end

  def destroy
    @lesson = Lesson.find(params[:id])
    @section = @lesson.section
    @lesson.destroy
    redirect_to chapter_path(@lesson.section.chapter)
  end

private
  def lesson_params
    params.require(:lesson).permit(:name, :content, :number)
  end

end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def index
    @sections = Section.all
    @chapter = Chapter.find(params[:id])
  end

  def show
    @chapter = Chapter.find(params[:chapter_id])
    @section = @chapter.sections.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chapters/index.html.erb
<h1>Courses At Epicodus</h1>

<% @chapters.each do |chapter| %>
  <p><%= link_to chapter.name, chapter_path(chapter) %></p>
<% end %>

app/views/chapters/show.html.erb
<h1>Course: <%= @chapter.name %></h1>


<h3>Weekly Sections Available:</h3>
<ul>
  <% @chapter.sections.each do |section| %>
    <li><%= link_to section.name, chapter_section_path(@chapter, section)%></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Learnhowtoprogram</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p><a href="/">Home</a> | <a href="/chapters/1">Vulcan</a> | <a href="/chapters/2">Q</a> | <a href="/chapters/3">Bajoran</a> | <a href="/chapters/4">Bajoran</a> </p>

    <%= yield %>
  </body>
</html>

app/views/lessons/_form.html.erb
<%= form_for [@section, @lesson] do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <%= f.label :content %><br>
  <%= f.text_field :content %><br>
  <%= f.label :number %><br>
  <%= f.text_field :number %><br>
  <%= f.label :section_id %><br>
  <%= f.collection_select :section_id, Section.order(:name), :id, :name, include_blank: true %><br>
  <%= f.submit %><br>
<% end %>

app/views/lessons/edit.html.erb
<h1>Edit <%= @lesson.name %> </h1>

<%= render 'form' %>

app/views/lessons/new.html.erb
<%= render 'form' %>

app/views/lessons/show.html.erb
<h1>Lesson: <%= @lesson.name %></h1>
<h1><%= @lesson.content %></h1>

<%= link_to "Edit Lesson", edit_section_lesson_path(@lesson) %>
<%= link_to "Delete Lesson", section_lesson_path(@lesson), :data => {
                                        :confirm => "you sure?",
                                        :method => "delete"} %>

app/views/sections/show.html.erb
<h1>Weekly Section: <%= @section.name %></h2>

<ul>
  <% @section.lessons.each do |lesson| %>
    <li><%= link_to lesson.name, section_lesson_path(@section, lesson) %></li>
  <% end %>
</ul>

<%= link_to 'Add Lesson', new_section_lesson_path(@section) %>